name: Publish Package

on:
  push:
    branches:   
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        name: "Install Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.3.8"
      -
        name: "Install dependencies"
        run: "flutter pub get"
#      -
#        name: Analyze
#        run: "flutter analyze"
#      -
#        name: "Run tests"
#        run: "flutter test"
#      -
#        env:
#          PUB_DEV_PUBLISH_ACCESS_TOKEN: "${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}"
#          PUB_DEV_PUBLISH_EXPIRATION: "${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}"
#          PUB_DEV_PUBLISH_REFRESH_TOKEN: "${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}"
#          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: "${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}"
#          SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
#        name: "Setup Pub Credentials"
#        run: "sh ./pub_login.sh\n"
#        shell: bash
#      -
#        name: "Check Publish Warnings"
#        run: "flutter pub publish --dry-run"
#      -
#        name: "Publish Package"
#        run: "flutter pub publish -f"

      -
        name: "Build Example Apk"
        run: "flutter build apk --target=lib/test_ci_project.dart"

      -
        name: "Upload apk to s3"
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '/home/runner/work/flutter_test_ci/build/app/outputs/flutter-apk/app-release.apk'


      -
        if: always()
        name: "Slack Notification"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test-github-actions
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_TITLE: "Deployment status - ${{ job.status }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GithuActionNotifier
          SLACK_ICON: https://www.freepnglogos.com/uploads/robot-png/sad-robot-icons-sad-robot-icon-download-iconhotm-0.png
